engines:
  rubocop:
    enabled: true
  brakeman:
   	enabled: true
  eslint:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      - ruby
      	#mass_threshold: 30
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- "**/tests/**/*"